CREATE DATABASE IF NOT EXISTS gold_landing_page CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gold_landing_page;

CREATE TABLE admins (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO admins VALUES (1,'admin','Administrator','$2y$10$DbDQ3J7Ud3Gtig/v/3SSl../O2t3ESXJJmzbNMV/.KxqcLFGz.Qgm','active',NOW(),NOW());

CREATE TABLE settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(120) NOT NULL UNIQUE, setting_value TEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO settings (setting_key,setting_value,created_at,updated_at) VALUES
('shop_name','Gajraj Jewellers and Saraf',NOW(),NOW()),('tagline','Jewellery, Trust and Gold Savings',NOW(),NOW()),('establishment_year','1998',NOW(),NOW()),('short_description','Gajraj Jewellers and Saraf brings trusted jewellery service with app-enabled gold-saving scheme access.',NOW(),NOW()),('shop_full_description','Gajraj Jewellers and Saraf serves families with BIS hallmarked jewellery, careful guidance, and transparent scheme records. Our official mobile app helps customers join monthly gold-saving schemes, track installments, view digital receipts, and stay updated with shop announcements.',NOW(),NOW()),('email','care@multigold.example',NOW(),NOW()),('phone','+91 98765 43210',NOW(),NOW()),('alternate_phone','+91 98765 43211',NOW(),NOW()),('whatsapp','919876543210',NOW(),NOW()),('address','Main Bazaar Road, Pune, Maharashtra, India',NOW(),NOW()),('business_hours','Mon-Sat 10:30 AM - 8:30 PM',NOW(),NOW()),('gst_number','27ABCDE1234F1Z5',NOW(),NOW()),('bis_details','BIS Hallmarked Jewellery Available',NOW(),NOW()),('android_url','#',NOW(),NOW()),('ios_url','#',NOW(),NOW()),('android_enabled','1',NOW(),NOW()),('ios_enabled','1',NOW(),NOW()),('app_heading','Manage your gold-saving scheme from your phone',NOW(),NOW()),('app_short_description','Join schemes, track installments, download receipts, and receive shop updates securely.',NOW(),NOW()),('primary_color','#8306A8',NOW(),NOW()),('secondary_color','#E4B83E',NOW(),NOW()),('accent_color','#F7EFFB',NOW(),NOW()),('heading_color','#211126',NOW(),NOW()),('text_color','#5E5064',NOW(),NOW()),('footer_color','#15051D',NOW(),NOW()),('button_radius','24',NOW(),NOW()),('card_radius','8',NOW(),NOW()),('announcement_enabled','1',NOW(),NOW()),('announcement_text','Download our official jewellery app and start your monthly gold-saving journey today',NOW(),NOW()),('announcement_link','#download',NOW(),NOW()),('announcement_bg','#8306A8',NOW(),NOW()),('announcement_text_color','#FFFFFF',NOW(),NOW()),('logo','uploads/logo/gajraj-logo-mark.avif',NOW(),NOW()),('full_logo','uploads/logo/gajraj-logo-full.avif',NOW(),NOW()),('meta_description','Premium jewellery shop app landing page for gold-saving and jewellery installment schemes.',NOW(),NOW());

CREATE TABLE sliders (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, desktop_image VARCHAR(255), mobile_image VARCHAR(255), heading VARCHAR(180) NOT NULL, subheading VARCHAR(180), description TEXT, primary_text VARCHAR(80), primary_link VARCHAR(255), secondary_text VARCHAR(80), secondary_link VARCHAR(255), text_align ENUM('left','center') DEFAULT 'left', overlay_opacity DECIMAL(3,2) DEFAULT 0.45, sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(status), INDEX(sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO sliders (heading,subheading,description,primary_text,primary_link,secondary_text,secondary_link,sort_order,status,created_at,updated_at) VALUES ('Save monthly and build your gold future','Official Jewellery App','Join gold-saving schemes, track installments, view receipts, and manage progress from your phone.','Download App','#download','View Scheme','gold-saving-scheme',1,'active',NOW(),NOW());

CREATE TABLE pages (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) NOT NULL, slug VARCHAR(180) NOT NULL UNIQUE, content MEDIUMTEXT NOT NULL, meta_title VARCHAR(180), meta_description TEXT, featured_image VARCHAR(255), show_in_footer TINYINT(1) DEFAULT 1, sort_order INT DEFAULT 0, status ENUM('active','draft') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(status), INDEX(sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO pages (title,slug,content,meta_title,meta_description,show_in_footer,sort_order,status,created_at,updated_at) VALUES
('Gold Saving Scheme','gold-saving-scheme','<p>Our monthly gold-saving scheme information is available through the official app. Customers can view installment records, payment history, maturity status, and redemption details.</p><p><strong>Disclaimer:</strong> Scheme terms, eligibility, payment schedule, maturity benefits, and redemption conditions are determined by the jewellery shop and may change as per shop policy.</p>','Gold Saving Scheme','Gold-saving scheme details and app download information.',1,1,'active',NOW(),NOW()),
('Privacy Policy','privacy-policy','<p>We collect only the information needed to provide app, scheme, enquiry, and customer-support services. Customer data is handled with care and never sold.</p>','Privacy Policy','Privacy policy for the jewellery app website.',1,2,'active',NOW(),NOW()),
('Terms and Conditions','terms-and-conditions','<p>Use of this website and app is subject to shop policies, applicable laws, and scheme-specific terms communicated by the jewellery shop.</p>','Terms and Conditions','Terms and conditions.',1,3,'active',NOW(),NOW()),
('Shipping Policy','shipping-policy','<p>This website does not provide online checkout. Shipping, where applicable, is handled directly by the jewellery shop.</p>','Shipping Policy','Shipping policy.',1,4,'active',NOW(),NOW()),
('Return Policy','return-policy','<p>Returns are governed by shop policy, product condition, invoice details, and applicable regulations.</p>','Return Policy','Return policy.',1,5,'active',NOW(),NOW()),
('Refund Policy','refund-policy','<p>Refunds, if applicable, are processed according to the jewellery shop policy and payment method rules.</p>','Refund Policy','Refund policy.',1,6,'active',NOW(),NOW()),
('Jewellery Care Policy','jewellery-care-policy','<p>Store jewellery separately, avoid chemicals, and visit the shop for professional cleaning and inspection.</p>','Jewellery Care Policy','Jewellery care guidance.',1,7,'active',NOW(),NOW()),
('Disclaimer','disclaimer','<p>Information on this website is for customer convenience. Final scheme, pricing, product, and redemption decisions remain with the jewellery shop.</p>','Disclaimer','Website disclaimer.',1,8,'active',NOW(),NOW());

CREATE TABLE certificates (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) NOT NULL, certificate_type VARCHAR(120), description TEXT, thumbnail VARCHAR(255), file_path VARCHAR(255), issue_date DATE NULL, expiry_date DATE NULL, download_enabled TINYINT(1) DEFAULT 1, sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(status), INDEX(sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE gallery (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) NOT NULL, category VARCHAR(120), image VARCHAR(255), description TEXT, sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(status), INDEX(sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE jewellery_categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL UNIQUE, image VARCHAR(255), description TEXT, sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(status), INDEX(sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO jewellery_categories (name,slug,description,sort_order,status,created_at,updated_at) VALUES ('Gold Jewellery','gold-jewellery','Elegant daily wear and festive gold pieces.',1,'active',NOW(),NOW()),('Bridal Jewellery','bridal-jewellery','Curated bridal ornaments for special occasions.',2,'active',NOW(),NOW()),('Mangalsutra','mangalsutra','Traditional and modern mangalsutra designs.',3,'active',NOW(),NOW()),('Bangles','bangles','Classic bangles and kada selections.',4,'active',NOW(),NOW());

CREATE TABLE testimonials (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, customer_name VARCHAR(160) NOT NULL, review TEXT NOT NULL, rating TINYINT DEFAULT 5, customer_image VARCHAR(255), city VARCHAR(120), sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO testimonials (customer_name,review,rating,city,sort_order,status,created_at,updated_at) VALUES ('Priya Shah','The app makes installment tracking very clear and easy for our family.',5,'Pune',1,'active',NOW(),NOW()),('Amit Patil','Trustworthy shop and helpful staff. Digital receipts are very convenient.',5,'Mumbai',2,'active',NOW(),NOW());
CREATE TABLE faqs (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, question VARCHAR(220) NOT NULL, answer TEXT NOT NULL, category VARCHAR(120), sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO faqs (question,answer,category,sort_order,status,created_at,updated_at) VALUES ('Can I track monthly installments in the app?','Yes. Customers can view scheme details, installment history, and digital receipts in the official app.','App',1,'active',NOW(),NOW()),('Are scheme benefits fixed?','Scheme terms and benefits are determined by the jewellery shop and communicated as per current policy.','Scheme',2,'active',NOW(),NOW());
CREATE TABLE contact_enquiries (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160), mobile VARCHAR(30), email VARCHAR(180), subject VARCHAR(180), message TEXT, status ENUM('new','contacted','resolved','closed') DEFAULT 'new', internal_note TEXT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE menu_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, label VARCHAR(120) NOT NULL, url VARCHAR(255) NOT NULL, target VARCHAR(20) DEFAULT '_self', sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX(status), INDEX(sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO menu_items (label,url,sort_order,status,created_at,updated_at) VALUES ('Home','',1,'active',NOW(),NOW()),('About','about-us',2,'active',NOW(),NOW()),('Gold Scheme','gold-saving-scheme',3,'active',NOW(),NOW()),('Mobile App','mobile-app',4,'active',NOW(),NOW()),('Certificates','certificates',5,'active',NOW(),NOW()),('Contact','contact-us',6,'active',NOW(),NOW());
CREATE TABLE shop_trust_points (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(160), description TEXT, icon VARCHAR(120), sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO shop_trust_points (title,description,icon,sort_order,status,created_at,updated_at) VALUES ('BIS Hallmarked Jewellery','Clear purity guidance and trusted jewellery standards.','fa-solid fa-certificate',1,'active',NOW(),NOW()),('Transparent Scheme Tracking','Customers can check installments and records in the app.','fa-solid fa-receipt',2,'active',NOW(),NOW()),('Personal Support','Our team helps with schemes, redemption, and jewellery selection.','fa-solid fa-headset',3,'active',NOW(),NOW());
CREATE TABLE scheme_steps (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(160), description TEXT, sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO scheme_steps (title,description,sort_order,status,created_at,updated_at) VALUES ('Download the app','Install the official Android or iOS app.',1,'active',NOW(),NOW()),('Register or login','Access your customer profile securely.',2,'active',NOW(),NOW()),('Join a scheme','Select available shop scheme options.',3,'active',NOW(),NOW()),('Pay monthly','Track installment records and receipts.',4,'active',NOW(),NOW()),('Redeem as per terms','Complete redemption according to shop policy.',5,'active',NOW(),NOW());
CREATE TABLE login_attempts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(120), ip_address VARCHAR(45), success TINYINT(1) DEFAULT 0, created_at DATETIME NOT NULL, INDEX(username), INDEX(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE app_screenshots (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, image VARCHAR(255), caption VARCHAR(160), sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE gallery_categories (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), sort_order INT DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE menus (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), location VARCHAR(80), status ENUM('active','inactive') DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
